### PR TITLE
Literally got annoying, literally.

### PR DESCRIPTION
**Pull request by EARoa**

### CODE REVIEW

**Comment by au5ton** [comment]
This is literally a popular opinion. Literally.

**Comment by amcdevitt97** [comment]
this was literally the best thing i've ever made. literally

**Comment by EARoa** [comment]
@amcdevitt97 you are literally evil. literally.

**Comment by JFKingsley** [comment]
Literally wiped from the face of the earth

**Comment by au5ton** [comment]
:+1:

**Pull request closed without merging**
